# -*- coding: utf-8 -*-
"""Stock Price trend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Umj1UhPzlfYoX2AHP3JUpxatWFjY8pdv
"""

import yfinance as yf
import pandas as pd
import plotly.graph_objects as go
from datetime import datetime, timedelta

def create_stock_dashboard(symbol="AAPL", period="1y"):
  stock = yf.Ticker(symbol)
  df = stock.history(period=period)
  fig = go.Figure(data=[go.Candlestick(x=df.index,
                                       open=df['Open'],
                                       high=df['High'],
                                       low=df['Low'],
                                       close=df['Close'])])
  df['MA20'] = df['Close'].rolling(window=20).mean()
  df['MA50'] = df['Close'].rolling(window=50).mean()
  fig.add_trace(go.Scatter(x=df.index, y=df['MA20'], name='20 Day MA'))
  fig.add_trace(go.Scatter(x=df.index, y=df['MA50'], name='50 Day MA'))
  fig.update_layout(title=f'{symbol} Stock Price Trend',
                       yaxis_title='Stock Price (USD)',
                      xaxis_title='Date')
  return fig
dashboard = create_stock_dashboard("AAPL", "1y")
dashboard.show()